name: "Get Terrafirma Github App Access Token"
description: "Get Terrafirma Github App Access Token"
author: "Terrafirma"

inputs:
  api_token:
    description: "Terrafirma Access Token"
    required: true

outputs:
  access_token:
    description: "Terrafirma Github App Access Token"
    value: ${{ steps.get_access_token.outputs.access_token }}

runs:
  using: "composite"
  steps:
    - name: "Get Terrafirma Github App Access Token"
      id: "get_access_token"
      shell: bash
      env:
        API_TOKEN: ${{ inputs.api_token }}
      run: |
        response=$(
          curl \
          --request GET \
          --url "https://terrafirma.linos.dev" \
          --header "Authorization: Bearer $API_TOKEN" \
          --header "Accept: application/json" \
          --fail-with-body
        )

        access_token=$(jq <<< "$response" -r '.accessToken')
        echo "::add-mask::$access_token"
        echo "access_token=${access_token}" >> "${GITHUB_OUTPUT}"
