name: "Google Get Secret Test"

on:
  pull_request:
    paths:
      - "actions/google-get-secret/**"
      - ".github/workflows/google-get-secret-tests.yml"
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: adelinosousa/terrafirma/actions/google-get-secret@feat/google-get-secret
        id: get-secret
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GOOGLE_WIP }}
          service_account: ${{ secrets.GOOGLE_SA }}
          secret_name: "github-key-test"

      - name: "Check output matches secret"
        run: |
          test "${{ steps.get-secret.outputs.secret }}" = "${{ secrets.GOOGLE_SECRET_TEST }}"
